# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
env:
- FLASK_APP=autoapp.py FLASK_DEBUG=1
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements/dev.txt
  - nvm install lts/*
  - npm install
before_script:
  - npm run lint
  - npm run build
  - flask lint
script: flask test
after_success:
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --tags
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
